---
- name: Convert GitLab Runner repository signing key to keyring format
  become: true
  ansible.builtin.command:
    argv:
      - gpg
      - --dearmor
      - --yes
      - --output
      - "{{ gitlab_runner_repo_key_path }}"
      - "{{ gitlab_runner_repo_key_asc_path }}"
  changed_when: true

- name: Restart GitLab Runner
  become: true
  ansible.builtin.service:
    name: "{{ gitlab_runner_service_name }}"
    state: restarted
