---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: shopdemo-platform
    app.kubernetes.io/managed-by: gitops
    shopdemo.io/environment: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
  labels:
    app.kubernetes.io/part-of: shopdemo-platform
    app.kubernetes.io/managed-by: gitops
    shopdemo.io/environment: platform
