---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: shopdemo
    shopdemo.io/environment: staging
spec:
  project: default
  source:
    repoURL: https://gitlab.com/ClementV78/shopdemo.git
    targetRevision: main
    path: gitops/environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: shopdemo-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
